# hyphy-absrel.sub

# Selection tests using HyPhy aBSREL method.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.10

log = hyphy-absrel.log
error = hyphy-absrel.err
output = hyphy-absrel.out

executable = hyphy-absrel.sh

batch_name = "hyphy-absrel"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue 1
