# raxml-boot.sub

# Generate tree bootstraps using RAxML-NG

universe = docker
docker_image = lucasnell/midgenomes:v1.0.4

log = raxml-boot_$(Process).log
error = raxml-boot_$(Process).err
output = raxml-boot_$(Process).out

executable = raxml-boot.sh
arguments = $(Process)

batch_name = "raxml-boot"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 8
request_memory = 12GB
request_disk = 20GB

queue 10
