# braker-rna.sub

# Annotate Tanytarsus gracilentus assembly using RNAseq reads

universe = docker
docker_image = lucasnell/midgenomes:v1.0.10

log = braker-rna-$(species).log
error = braker-rna-$(species).err
output = braker-rna-$(species).out

executable = braker-rna.sh
arguments = "$(all_args)"

batch_name = "braker-rna-$(species)"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 24GB
request_disk = 100GB


queue species, all_args from rna-args.txt
