# shasta.sub

# Assemble Tanytarsus gracilentus genome

universe = vanilla
log = shasta/shasta.log
error = shasta/shasta.err

executable = shasta/shasta.sh
output = shasta/shasta.out

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs. The last of these lines *would* be
##  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = shasta/shasta-Linux-0.7.0.gz,shasta/shasta.conf

## IMPORTANT! Require execute servers that have /staging access and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 32
request_disk = 200GB

## From the shasta documentation:
##
## > Memory requirements for optimal performance are roughly proportional
## > to genome size and coverage, and are around 4 to 6 bytes per input base.
## > This only counts input bases that are used in the assembly...
##
## So for a 112 Mb genome at 100x coverage, 67.2 GB should be enough.
##
request_memory = 80GB

# Tell HTCondor to run 1 instance of this job:
queue 1
