# medaka.sub

# Run medaka to polish the Tanytarsus gracilentus assembly

universe = vanilla

log = medaka/medaka.log
error = medaka/medaka.err
executable = medaka/medaka.sh
output = medaka/medaka.out

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs. The last of these lines *would* be
##  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = medaka_bin.tar.gz

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 36
request_memory = 72GB
request_disk = 500GB

# Tell HTCondor to run 1 instance of this job:
queue 1
