# fastp-rna.sub

# Align adult midge RNA reads to the Tanytarsus gracilentus assembly

universe = docker
docker_image = lucasnell/tany_genomics:v0.2

log = fastp-rna/fastp-rna_$(readbase).log
error = fastp-rna/fastp-rna_$(readbase).err
output = fastp-rna/fastp-rna_$(readbase).out

executable = fastp-rna/fastp-rna.sh
arguments = $(readbase)

batch_name = "fastp-rna"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 16GB
request_disk = 60GB


# Run one instance of this job per line in `fastp-rna/readbases.txt`
queue readbase from fastp-rna/readbases.txt
