# fastp-rna.sub

# Trim RNA reads

universe = docker
docker_image = lucasnell/tany_genomics:v0.5

log = fastp-rna_$(readbase).log
error = fastp-rna_$(readbase).err
output = fastp-rna_$(readbase).out

executable = fastp-rna.sh
arguments = $(readbase)

batch_name = "fastp-rna"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 60GB

queue readbase from readbases.txt
