# fastp-dna.sub

# trim Illumina DNA reads

universe = docker
docker_image = lucasnell/midgenomes:v1.0.6

log = fastp-dna_$(readtar).log
error = fastp-dna_$(readtar).err
output = fastp-dna_$(readtar).out

executable = fastp-dna.sh
arguments = $(readtar)

batch_name = "fastp-dna"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 60GB

# Run one instance of this job per line in `readtars.txt`
queue readtar from readtars.txt
