# fastp-dna.sub

# trim Pool-seq DNA reads

universe = docker
docker_image = lucasnell/tany_genomics:v0.5

log = fastp-dna_$(readbase).log
error = fastp-dna_$(readbase).err
output = fastp-dna_$(readbase).out

executable = fastp-dna.sh
arguments = $(readbase)

batch_name = "fastp-dna"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 16GB
request_disk = 60GB


# Run one instance of this job per line in `readbases.txt`
queue readbase from readbases.txt
