# fastp-rna.sub

# Trim RNA reads

universe = docker
docker_image = lucasnell/midgenomes:v1.0.1

log = fastp-rna_$(readtar).log
error = fastp-rna_$(readtar).err
output = fastp-rna_$(readtar).out

executable = fastp-rna.sh
arguments = $(readtar)

batch_name = "fastp-rna"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 60GB

queue readtar from readtars.txt
