# braker-prot.sub

# Annotate genome assembly using dipteran proteins from OrthoDB database

universe = docker
docker_image = lucasnell/midgenomes:v1.0.5

log = braker-prot-$(species).log
error = braker-prot-$(species).err
output = braker-prot-$(species).out

executable = braker-prot.sh
arguments = -p $(species) /staging/lnell/annotations/$(species)_contigs_masked.fasta.gz

batch_name = "braker-prot-$(species)"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 48GB
request_disk = 200GB

queue species from prot-species.txt
