# edta.sub

# Create de novo repeat library for the Tanytarsus gracilentus assembly

universe = docker
docker_image = lucasnell/tanyssembly:v0.0.1

log = edta.log
error = edta.err
output = edta.out

executable = edta.sh

batch_name = "edta"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 24
request_memory = 48GB
request_disk = 100GB


queue 1
