# mantis.sub

# Gene functional analysis using mantis.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.5

log = mantis.log
error = mantis.err
output = mantis.out

executable = mantis.sh
batch_name = "mantis"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

# (Uses lots of disk space because of databases downloaded)
request_cpus = 32
request_memory = 50GB
request_disk = 300GB

queue 1
