# mantis.sub

# Gene functional analysis using mantis.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.6

log = mantis-$(species).log
error = mantis-$(species).err
output = mantis-$(species).out

executable = mantis.sh
arguments = -p $(species) -n $(ncbi) $(proteins)

batch_name = "mantis-$(species)"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

# (Uses lots of disk space because of databases downloaded)
request_cpus = 32
request_memory = 80GB
request_disk = 300GB

queue species, ncbi, proteins from to-mantis.txt
