# repeats.sub

# Create library of repetitive elements using RepeatModeler.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.10

log = repeats-$(species).log
error = repeats-$(species).err
output = repeats-$(species).out

executable = repeats.sh
arguments = -p $(species) /staging/lnell/assemblies/$(species)_assembly.fasta.gz

batch_name = "repeats-$(species)"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue species from spp-abbrevs.txt


