# repeats-Aaegyp-model.sub

# Create library of repetitive elements in Aedes aegypti assembly using RepeatModeler.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.8

log = repeats-Aaegyp-model.log
error = repeats-Aaegyp-model.err
output = repeats-Aaegyp-model.out

executable = repeats-Aaegyp-model.sh

batch_name = "repeats-Aaegyp-model"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 80
request_memory = 120GB
request_disk = 100GB

queue 1
