# canu.sub

# Align reads for Tanytarsus gracilentus genome

universe = vanilla
log = canu/assembly.log
error = canu/assembly.err

executable = canu/canu.sh
output = canu/assembly.out

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs. The last of these lines *would* be
##  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = canu/canu-2.1.1.Linux-amd64.tar.xz

## IMPORTANT! Require execute servers that have Gluster and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 32
request_memory = 32GB
request_disk = 5000GB

# Tell HTCondor to run 1 instance of this job:
queue 1
