# pepper.sub

# Polish Tanytarsus gracilentus genome

universe = docker
docker_image = kishwars/pepper_deepvariant:r0.4

log = pepper/pepper.log
error = pepper/pepper.err

executable = pepper/pepper.sh
output = pepper/pepper.out

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs. The last of these lines *would* be
##  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
## transfer_input_files =

## IMPORTANT! Require execute servers that have /staging access and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 32
request_memory = 80GB
request_disk = 200GB

# Tell HTCondor to run 1 instance of this job:
queue 1
