# P_RNA.sub

# Run P_RNA to account for heterozygosity in the Tanytarsus
# gracilentus assembly

universe = vanilla

log = P_RNA/P_RNA.log
error = P_RNA/P_RNA.err
executable = P_RNA/P_RNA.sh
output = P_RNA/P_RNA.out

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = P_RNA/P_RNA_progs.tar.gz

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 24
request_memory = 50GB
request_disk = 100GB

# Tell HTCondor to run 1 instance of this job:
queue 1
