# busco.sub

# BUSCO score for Tanytarsus genome

universe = docker
docker_image = ezlabgva/busco:v5.2.2_cv1


log = busco/busco.log
error = busco/busco.err
executable = busco/busco.sh
output = busco/busco.out

#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = redundans_contigs.fasta.gz

## IMPORTANT! Require execute servers that have CentOS 7
requirements = (OpSysMajorVer == 7)

#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 12
# MB:
request_memory = 10000
# KB:
request_disk = 1000000


# Tell HTCondor to run 1 instance of this job:
queue 1
