# busco.sub

# BUSCO score for Tanytarsus genome

universe = docker
docker_image = ezlabgva/busco:v5.2.2_cv1


log = busco/busco.log
error = busco/busco.err
executable = busco/busco.sh
output = busco/busco.out

#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = scaffolds.fasta.gz

## IMPORTANT! Require execute servers that have CentOS 7
requirements = (OpSysMajorVer == 7)

#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 12
request_memory = 12GB
request_disk = 10GB



# Tell HTCondor to run 1 instance of this job:
queue 1
