# besst.sub

# Run BESST_RNA to scaffold the Tanytarsus gracilentus assembly
# using RNA-seq reads

universe = vanilla

log = besst/besst.log
error = besst/besst.err
executable = besst/besst.sh
output = besst/besst.out

batch_name = "besst"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = besst/BESST_RNA.tar.gz

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 4
request_memory = 40GB
request_disk = 200GB

# Tell HTCondor to run 1 instance of this job:
queue 1

