# dentist.sub

# DENTIST to fill gaps in Tanytarsus gracilentus genome

universe = vanilla

log = dentist/dentist_$(fasta).log
error = dentist/dentist_$(fasta).err
output = dentist/dentist_$(fasta).out

executable = dentist/dentist.sh
arguments = $(fasta)

batch_name = "dentist"

#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = dentist/dentist.v3.0.0.x86_64.tar.gz, dentist/dentist.yml, dentist/snakemake.yml

## IMPORTANT! Require execute servers that have /staging access and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 32
request_memory = 64GB
request_disk = 200GB


# Run one instance of this job per line in `dentist/fastas.txt`
queue fasta from dentist/fastas.txt
