# besst.sub

# Run BESST_RNA to scaffold the Tanytarsus gracilentus assembly
# using RNA-seq reads

universe = docker
docker_image = lucasnell/tany_scaff:v0

log = besst/$(fasta)_besst.log
error = besst/$(fasta)_besst.err
output = besst/$(fasta)_besst.out

executable = besst/besst.sh
arguments = $(fasta)

batch_name = "besst"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = besst/BESST_RNA.tar.gz

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 4
request_memory = 8GB
request_disk = 50GB

# Run one instance of this job per line in `besst/fastas.txt`
queue fasta from besst/fastas.txt

