# busco.sub

# BUSCO score for Tanytarsus genome

# This will run	one instance of	BUSCO for each line in
# the file `busco/fastas.txt`

universe = docker
docker_image = ezlabgva/busco:v5.2.2_cv2


log = busco/busco__$(fasta).log
error = busco/busco__$(fasta).err
output = busco/busco__$(fasta).out

executable = busco/busco.sh
arguments = $(fasta)

batch_name = busco

#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have /staging access and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 24
request_memory = 8GB
request_disk = 50GB

# Run one instance of this job per line in `busco/fastas.txt`
queue fasta from busco/fastas.txt
