# fastp.sub

# Align adult midge RNA reads to the Tanytarsus gracilentus assembly

universe = docker
docker_image = lucasnell/tany_scaff:v0

log = fastp/fastp_$(readbase).log
error = fastp/fastp_$(readbase).err
output = fastp/fastp_$(readbase).out

executable = fastp/fastp.sh
arguments = $(readbase)

batch_name = "fastp"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 16GB
request_disk = 60GB


# Run one instance of this job per line in `fastp/readbases.txt`
queue readbase from fastp/readbases.txt
