# hisat2.sub

# Align adult midge RNA reads to the Tanytarsus gracilentus assembly

universe = docker
docker_image = lucasnell/tany_scaff:v0

log = hisat2/hisat2_$(fasta).log
error = hisat2/hisat2_$(fasta).err
output = hisat2/hisat2_$(fasta).out

executable = hisat2/hisat2.sh
arguments = $(fasta)

batch_name = "hisat2"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 32
request_memory = 64GB
request_disk = 350GB


# Run one instance of this job per line in `hisat2/fastas.txt`
queue fasta from hisat2/fastas.txt
