# longstitch.sub

# Run longstitch to scaffold the Tanytarsus gracilentus assembly

universe = docker
docker_image = lucasnell/tany_genomics:v0.2

log = longstitch/$(fasta)_longstitch.log
error = longstitch/$(fasta)_longstitch.err
output = longstitch/$(fasta)_longstitch.out

executable = longstitch/longstitch.sh
arguments = $(fasta)

batch_name = "longstitch"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 16GB
request_disk = 50GB

# Run one instance of this job per line in `longstitch/fastas.txt`
queue fasta from longstitch/fastas.txt
