# longstitch.sub

# Run longstitch to scaffold the Tanytarsus gracilentus assembly

universe = docker
docker_image = quay.io/biocontainers/longstitch:1.0.1--hdfd78af_2


log = longstitch/$(fasta)_longstitch.log
error = longstitch/$(fasta)_longstitch.err
output = longstitch/$(fasta)_longstitch.out

executable = longstitch/longstitch.sh
arguments = $(fasta)

batch_name = "longstitch"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = summ_scaffs

## IMPORTANT! Require execute servers that have access to staging and CentOS 7
requirements = (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 12GB
request_disk = 40GB

# Run one instance of this job per line in `longstitch/fastas.txt`
queue fasta from longstitch/fastas.txt
