# prna.sub

# Run P_RNA_Scaffolder to scaffold the Tanytarsus gracilentus assembly
# using RNA-seq reads

universe = docker
docker_image = lucasnell/tany_genomics:v0.2

log = prna/$(fasta)_prna.log
error = prna/$(fasta)_prna.err
output = prna/$(fasta)_prna.out

executable = prna/prna.sh
arguments = $(fasta)

batch_name = "prna"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = prna/P_RNA_scaffolder.tar.gz

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 8GB
request_disk = 300GB

# Run one instance of this job per line in `prna/fastas.txt`
queue fasta from prna/fastas.txt
