# purgedups.sub

# Run purge_dups to account for heterozygosity in the Tanytarsus
# gracilentus assembly

universe = docker
docker_image = lucasnell/tany_genomics:v0.5.4

log = purgedups.log
error = purgedups.err
executable = purgedups.sh
output = purgedups.out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
request_memory = 40GB
request_disk = 100GB

queue 1
