# epd.sub

# Explore options for purge_dups

universe = docker
docker_image = lucasnell/tany_genomics:v0.2

log = epd/epd.log
error = epd/epd.err
output = epd/epd.out

## executable = epd/epd.sh


## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging
requirements = (Target.HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 24
request_memory = 40GB
request_disk = 100GB

# Tell HTCondor to run 1 instance of this job:
queue 1
