# epd_f.sub

# Explore options for purge_dups

universe = docker
docker_image = lucasnell/tany_genomics:v0.3

log = epd_f_$(f).log
error = epd_f_$(f).err
output = epd_f_$(f).out

executable = epd_f.sh
arguments = $(f)

batch_name = "epd_f"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 12
request_memory = 16GB
request_disk = 80GB


queue f from fvals.txt
