# epd.sub

# Explore options for purge_dups

universe = docker
docker_image = lucasnell/tany_genomics:v0.5.1

log = epd_a-$(a)_f-$(f).log
error = epd_a-$(a)_f-$(f).err
output = epd_a-$(a)_f-$(f).out

executable = epd.sh
arguments = contigs_shasta_pepper-hap1.fasta $(a) $(f)

batch_name = "epd"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 12
request_memory = 16GB
request_disk = 80GB


queue a,f from af_vals.txt
