# necat.sub

# Assemble Tanytarsus gracilentus genome using NECAT

universe = docker
docker_image = lucasnell/tanyssembly:v0.0.1

log = necat.log
error = necat.err
output = necat.out

executable = necat.sh

batch_name = "necat"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 65GB
request_disk = 150GB

queue 1
