# nextpolish.sub

# Polish assembly using Illumina reads via NextPolish

universe = docker
docker_image = lucasnell/midgenomes:v1.0.8

log = nextpolish_$(assembly)_r$(rounds).log
error = nextpolish_$(assembly)_r$(rounds).err
output = nextpolish_$(assembly)_r$(rounds).out

executable = nextpolish.sh
arguments = -i $(reads) -r $(rounds) $(assembly).fasta

batch_name = "nextpolish"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue assembly, reads, rounds from assemblies.txt
