# ont-polish.sub

# Polish assembly using ONT reads and programs Racon and medaka

universe = docker
docker_image = lucasnell/midgenomes:v1.0.10

log = ont-polish_$(assembly)_r$(n_racon)_m$(n_medaka).log
error = ont-polish_$(assembly)_r$(n_racon)_m$(n_medaka).err
output = ont-polish_$(assembly)_r$(n_racon)_m$(n_medaka).out

executable = ont-polish.sh
arguments = -n $(nano_reads) -r $(n_racon) -m $(n_medaka) $(assembly).fasta

batch_name = "ont-polish"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
request_memory = 80GB
request_disk = 100GB

queue assembly, nano_reads, n_racon, n_medaka from assemblies.txt
