# ont-polish.sub

# Polish assembly using ONT reads and programs Racon and medaka

universe = docker
docker_image = lucasnell/tanyssembly:v0.0.1

log = ont-polish_$(assembly)_$(n_rakon)rakon.log
error = ont-polish_$(assembly)_$(n_rakon)rakon.err
output = ont-polish_$(assembly)_$(n_rakon)rakon.out

executable = ont-polish.sh
arguments = $(assembly).fasta $(n_rakon)

batch_name = "ont-polish"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
request_memory = 80GB
request_disk = 100GB

queue assembly, n_rakon from assemblies.txt
