# pilon.sub

# Polish assembly using Illumina reads via pilon

universe = docker
docker_image = lucasnell/tany_genomics:v0.5.2

log = pilon_$(assembly).log
error = pilon_$(assembly).err
output = pilon_$(assembly).out

executable = pilon.sh
arguments = $(assembly)

batch_name = "pilon"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 64GB
request_disk = 100GB

queue assembly from assemblies.txt
