# combine-snapes.sub

# combines SNAPE output from all quality-passing gSYNC
# objects into three:
# one for temporal samples, one for spatial samples, and one for all.


universe = vanilla

log = combine-snapes.log
error = combine-snapes.err
output = combine-snapes.out

executable = combine-snapes.sh

batch_name = "combine-snapes"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (Target.HasCHTCStaging == true)

request_cpus = 2
request_memory = 4GB
request_disk = 80GB

queue 1
