# mpileup.sub

# prep aligned Pool-seq DNA reads and call `samtools mpileup`

universe = docker
docker_image = lucasnell/tany_genomics:v0.5

log = mpileup_$(readbase).log
error = mpileup_$(readbase).err
output = mpileup_$(readbase).out

executable = mpileup.sh
arguments = $(readbase)

batch_name = "mpileup"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (Target.HasCHTCStaging == true)

request_cpus = 4
request_memory = 8GB
request_disk = 50GB

queue readbase from readbases.txt
