# mpileup.sub

# align Pool-seq DNA reads

universe = docker
docker_image = lucasnell/tany_genomics:v0.4

log = mpileup_$(readbase).log
error = mpileup_$(readbase).err
output = mpileup_$(readbase).out

executable = mpileup.sh
arguments = $(readbase)

batch_name = "mpileup"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (Target.HasCHTCStaging == true)

request_cpus = 4
request_memory = 16GB
request_disk = 80GB

queue readbase from readbases.txt
