universe =                  docker
docker_image =              lucasnell/tany_genomics:v0.3
log =                       besst/$(fasta)_besst.log
error =                     besst/$(fasta)_besst.err
output =                    besst/$(fasta)_besst.out
executable =                besst.sh
arguments =                 $(fasta)
should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
requirements =              (Target.HasCHTCStaging == true)
request_cpus =              32
request_memory =            16GB
request_disk =              150GB
queue 1
