universe =                  vanilla
log =                       dentist/$(fasta)D.log
error =                     dentist/$(fasta)D.err
output =                    dentist/$(fasta)D.out
executable =                dentist.sh
arguments =                 $(fasta) $(join) $(coverage)
should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
requirements =              (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)
request_cpus =              24
request_memory =            16GB
request_disk =              60GB
queue 1
