universe =                  vanilla
log =                       dentist/$(fasta)_dentist.log
error =                     dentist/$(fasta)_dentist.err
output =                    dentist/$(fasta)_dentist.out
executable =                dentist.sh
arguments =                 $(fasta)
should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
transfer_input_files =      dentist/dentist_files.tar.gz, summarize.sh
requirements =              (Target.HasCHTCStaging == true) && (OpSysMajorVer == 7)
request_cpus =              24
request_memory =            16GB
request_disk =              60GB
queue 1
