universe =                  docker
docker_image =              lucasnell/tany_genomics:v0.3
log =                       summarize/$(fasta)_summarize.log
error =                     summarize/$(fasta)_summarize.err
output =                    summarize/$(fasta)_summarize.out
executable =                summarize.sh
arguments =                 $(fasta)
should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
requirements =              (Target.HasCHTCStaging == true)
request_cpus =              24
request_memory =            12GB
request_disk =              50GB
queue 1
