universe =                  docker
docker_image =              lucasnell/tany_genomics:v0.5.8
log =                       $(fasta)_besst.log
error =                     $(fasta)_besst.err
output =                    $(fasta)_besst.out
executable =                besst.sh
arguments =                 $(fasta)
batch_name =                "besst"
should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
requirements =              (Target.HasCHTCStaging == true)
request_cpus =              32
request_memory =            16GB
request_disk =              150GB

queue fasta from assemblies.txt

