# mcmctree.sub

# Run MCMCTree interactively to create time-calibrated tree.


universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = mcmctree.log

batch_name = "mcmctree"

# In the latest version of HTCondor on CHTC, interactive jobs require an executable.
# If you do not have an existing executable, use a generic linux command like hostname as shown below.
executable = /usr/bin/hostname

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

# 24 threads is a good option to multithread across the 48 partitions
request_cpus = 24
request_memory = 32GB
request_disk = 100GB

queue 1
