# modeltest.sub

# Model selection using ModelTest-NG

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = modeltest.log
error = modeltest.err
output = modeltest.out

executable = modeltest.sh

batch_name = "modeltest"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 24
request_memory = 48GB
request_disk = 100GB

queue 1
