# modelfinder.sub

# Find optimum model and partition scheme using IQ-TREE's ModelFinder

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = modelfinder.log
error = modelfinder.err
output = modelfinder.out

executable = modelfinder.sh

batch_name = "modelfinder"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 18
request_memory = 32GB
request_disk = 100GB

queue 1
