# phylo.sub

# Single submission script for interactive jobs used to construct phylogeny.


universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = phylo.log

batch_name = "phylo"

# In the latest version of HTCondor on CHTC, interactive jobs require an executable.
# If you do not have an existing executable, use a generic linux command like hostname as shown below.
executable = /usr/bin/hostname

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
request_memory = 32GB
request_disk = 50GB

queue 1
