# raxml-mf.sub

# Create phylogeny using RAxML-NG, using ModelFinder scheme/models as inputs.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml-mf.log
error = raxml-mf.err
output = raxml-mf.out

executable = raxml-mf.sh

batch_name = "raxml-mf"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue 1
