# raxml-mt-combine.sub

# Combine multiple runs of RAxML-NG.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml-mt-combine.log
error = raxml-mt-combine.err
output = raxml-mt-combine.out

notification = Complete
# notify_user = <email-address>

executable = raxml-mt-combine.sh
arguments = $(Process)

batch_name = "raxml-mt-combine"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 4
request_memory = 16GB
request_disk = 100GB

queue 1
