# raxml-boot.sub

# Generate tree bootstraps using RAxML-NG

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml-boot_$(Process).log
error = raxml-boot_$(Process).err
output = raxml-boot_$(Process).out

executable = raxml-boot.sh
arguments = $(Process)

batch_name = "raxml-boot"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
request_memory = 32GB
request_disk = 100GB

queue 10
