# raxml-mt-run.sub

# Create phylogeny using RAxML-NG, using ModelTest-NG models as inputs
# and splitting the task into 10 separate jobs.

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml-mt-run-$(Process).log
error = raxml-mt-run-$(Process).err
output = raxml-mt-run-$(Process).out

notification = Complete

executable = raxml-mt-run.sh
arguments = $(Process)

# automatically release jobs held for exceeding resources up to 5 times
periodic_release = (JobStatus == 5) && (HoldReasonCode == 34) && (NumJobStarts < 5)

# if the job has run before, request either a multiple of the memory
# used by a previous run, or the default, whichever is larger.
# Else, use the default.
request_memory = ifthenelse(MemoryUsage =!= undefined, MAX({MemoryUsage * 3/2, 32000}), 32000)


batch_name = "raxml-mt-run"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 16
## request_memory = 24GB
request_disk = 100GB

queue 10
