# raxml-boot.sub

# Generate tree bootstraps using RAxML-NG

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml-boot.log
error = raxml-boot.err
output = raxml-boot.out

notification = Complete

executable = raxml-boot.sh

batch_name = "raxml-boot"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 64
request_memory = 48GB
request_disk = 100GB

queue 1
