# raxml.sub

# Create phylogeny using RAxML-NG

universe = docker
docker_image = lucasnell/midgenomes:v1.0.12

log = raxml_$(Process).log
error = raxml_$(Process).err
output = raxml_$(Process).out

# notification = Complete
# notify_user = <email-address>

executable = raxml.sh
arguments = $(Process)

batch_name = "raxml"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (Target.HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue 3
